### ISSUE TITLE
SVA python issue

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#155]
Hi @jcfr 

I am encountering this error when I try to run sva from a compiled version of SlicerSALT.
Ideas?

![Screenshot from 2019-04-26 11-23-43](https://user-images.githubusercontent.com/2599368/56818938-bebae780-6816-11e9-8171-ff15a0565e8a.png)

cc: @lopezmt

**Comment by jcfr** [comment]
Gotcha. The header  at the top of the python script is incorrect.

Waiting we update the code, you could locally modify the header of these files:
* `lib/SlicerSALT-4.11/qt-scripted-modules/shapepca`
* `lib/SlicerSALT-4.11/qt-scripted-modules/MFSDA_createShapes.py`
* `lib/SlicerSALT-4.11/qt-scripted-modules/MFSDA_run`
* `lib/SlicerSALT-4.11/qt-scripted-modules/MFSDA_createShapes`
* `lib/SlicerSALT-4.11/qt-scripted-modules/MFSDA_run.py`

to include `!/usr/bin/env python` instead of `!/usr/bin/env python-real`

**Comment by bpaniagua** [comment]
more info: It does not happen on the package uploaded [to our download folder](https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5bd85a568d777f06b9402dad).

**Comment by jcfr** [comment]
I see. Will get back with  a different fix then.
