### ISSUE TITLE
Update ShapeVariationAnalyzer version and simplify its integration

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#224]
Since following the merge of https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/pull/50, an external project installing scikit-learn is provided in the extension, after updating the version of `ShapeVariationAnalyzer` used in SlicerSALT, the following files should be removed:
* [SuperBuild/ShapeVariationAnalyzer-requirements.txt](https://github.com/Kitware/SlicerSALT/blob/35cf669847b6b87438b77fe153be2a2248465fec/SuperBuild/ShapeVariationAnalyzer-requirements.txt)
* [SuperBuild/External_python-ShapeVariationAnalyzer-requirements.cmake](https://github.com/Kitware/SlicerSALT/blob/35cf669847b6b87438b77fe153be2a2248465fec/SuperBuild/External_python-ShapeVariationAnalyzer-requirements.cmake)

**Comment by bpaniagua** [comment]
@vicory Could you please do this?
Thanks!

**Comment by vicory** [comment]
Simply updating the SVA SALT is using does not work. First, the build fails because it tries to install scikit-learn before pip is built. 

Making sure pip is available first makes the SVA build complain because there is not a required hash listed for scipy, which scikit-learn depends on. For SALT this is pulled in separately by MFSDA, not sure how this will work building as an extension for Slicer proper.

**Comment by jcfr** [comment]
>  it tries to install scikit-learn before pip is built.

Thanks for the feedback, this makes sense. I will submit a PR to address this after my current meeting.

**Comment by bpaniagua** [comment]
@jcfr i believe this issue can be closed, can you please confirm?

**Comment by jcfr** [comment]
Closing. Fixed through https://github.com/Kitware/SlicerSALT/commit/047bc8b18d48275a22f1636b2051443b42f86979, https://github.com/Kitware/SlicerSALT/commit/047bc8b18d48275a22f1636b2051443b42f86979 and https://github.com/Kitware/SlicerSALT/commit/83fac8330baf19ca6f524fcedc613a865d7be98e
