### ISSUE TITLE
S-rep hypothesis testing work

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#291]
1. Generate a module that does batch fits of s-reps
2. Read the documentation sent by Mohsen incl. paper describing the method and R-codebase
3. Generate a module for hypothesis testing in S-reps

**Comment by Connor-Bowley** [comment]
The new pipeline creator is a good candidate for this. The (unmerged) [new pipeline creator](https://github.com/allemangD/SlicerPipelines/pull/1) plus the work in [this commit](https://github.com/KitwareMedical/SlicerSkeletalRepresentation/commit/60312db23d0272c6e51faaeeeeb64e1322879339) can make a module that does initial-fit + refinement. The batch processing part of the new pipeline infrastructure has not been started however.

**Comment by HarryDC** [comment]
Yea I looked at the two pipelines, i think those are good to go, I have the creator in a state too where it can potentially store multiple output paramters/nodes. And we are ready to create a pipeline from the two parts. 

I can put up a SlicerSalt branch that has the connors branch in SRep and my pipelines working branch tied together, i'll set up a combined pipeline so that all the parameters are exposed in the Creator/Refiner pipeline, you should then be able to create a .csv with all the input nodes and input parameters and run that through the Creator/Refiner

**Comment by HarryDC** [comment]
@vicory Where should the created combined module live ? Checked into SREP as a module or as something under SlicerSALT ?

**Comment by bpaniagua** [comment]
Hi Harry, The new module should live under s-reps.

**Comment by HarryDC** [comment]
Quick update, it took a bit of hand editing (the annotations that limit the inputs and confer the defaults aren't copied by the pipeline creator) but this is the Combined Module. 

![image](https://github.com/Kitware/SlicerSALT/assets/1878111/b936b6fd-29e4-4f49-860e-bd7f647c3aff)

I'll push updates Slicer/SRep/Pipenline branches so you can test this

**Comment by bpaniagua** [comment]
https://github.com/Kitware/SlicerSALT/commit/9b5ad911cef11e91dba13104da0ae2d4ffe09e8e
